name: just_the_tooltip
description: A multi directional tooltip used to display any content with
  inbuilt support for list views
version: 0.0.12
homepage: https://github.com/Nolence/just_the_tooltip

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
